### ISSUE TITLE
Login, promptToInstall: true, throws Java exception on Android

### ISSUE THREAD

**Issue by denisx304** [zyra/cordova-plugin-linkedin#28]
Hello,

I just tried the followind piece of code:
`var scopes = ['r_basicprofile', 'r_emailaddress'];
cordova.plugins.LinkedIn.login(scopes, true, function(o) {
			console.log(o);
		}, function() {
			console.error(error);
		});`

and this is what I'm getting in Android Studio:
`java.lang.NoClassDefFoundError: Failed resolution of: Lcom/linkedin/android/mobilesdk/R$string;
    at com.linkedin.platform.internals.AppStore.goAppStore(AppStore.java:20)
    at com.linkedin.platform.LISessionManager.init(LISessionManager.java:115)
    at com.zyramedia.cordova.linkedin.LinkedIn.init(LinkedIn.java:120)
    at com.zyramedia.cordova.linkedin.LinkedIn.execute(LinkedIn.java:61)
    at org.apache.cordova.CordovaPlugin.execute(CordovaPlugin.java:98)
    at org.apache.cordova.PluginManager.exec(PluginManager.java:132)
    at org.apache.cordova.CordovaBridge.jsExec(CordovaBridge.java:57)
    at org.apache.cordova.engine.SystemExposedJsApi.exec(SystemExposedJsApi.java:41)
    at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
    at org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:7)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:168)
    at android.os.HandlerThread.run(HandlerThread.java:61)
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.linkedin.android.mobilesdk.R$string" on path: DexPathList[[zip file "/data/app/ro.atlas.app-1/base.apk"],nativeLibraryDirectories=[/data/app/ro.atlas.app-1/lib/arm, /system/lib, /vendor/lib, system/vendor/lib, system/vendor/lib/egl, system/lib/hw]]
    at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
	... 13 more
	Suppressed: java.lang.ClassNotFoundException: com.linkedin.android.mobilesdk.R$string
    at java.lang.Class.classForName(Native Method)
    at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
    at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
		... 14 more
	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available`

**Comment by VonHirsch** [comment]
Same issue, is it looking for some configuration string?

**Comment by VonHirsch** [comment]
Sorry for spamming this thread, I've tried a ton of workarounds (mostly gradle configs in android studio) for this but no joy.  When I analyze the APK it does contain a reference to com.linkedin.android.mobilesdk.R$string.  I thought adding the strings to the resources file might fix it, but that didn't work either.  This is occurring with node v8.9.3, ionic 3.19.1, cordova 8.0.0, Android 7.0 Nougat.  This is currently a showstopper for my configuration.

**Comment by Wolf00Bomber** [comment]
Any fix for this issue? Still working on it.

**Comment by Wolf00Bomber** [comment]
nstall the Linked In App on the Device, and then these issues will be fixed. I did that and now i am seeing the Login Permisison Prompt. Sheers :)
